server.port: 8085
spring.application.name: SmartMcpClient
spring.ai.openai.api-key: ${OPEN_AI_API_KEY}
spring.ai.openai.chat.options.model: gpt-4o-mini
spring.ai.mcp.client.streamable-http.connections.server1.url: http://localhost:8081
spring.ai.mcp.client.streamable-http.connections.server1.endpoint: /mcp
spring.ai.mcp.client.type: sync


logging.pattern.console: "%green(%d{yyyy-MM-dd HH:mm:ss}) %blue(%level) %red([%thread]) - %msg%n"
logging.level.org.springframework.ai.chat.client.advisor: DEBUG
logging.level.org.springframework.ai.mcp: DEBUG
logging.level.org.springframework.ai.client: DEBUG


app.mcp.security.api-key: ${MCP_API_KEY}